const VOICES = [
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, AIGenerate1Neural)', ShortName: 'en-US-AIGenerate1Neural', Gender: 'Male', Locale: 'en-US', FriendlyName: 'Microsoft AIGenerate1Neural (Male) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, AndrewNeural)', ShortName: 'en-US-AndrewNeural', Gender: 'Male', Locale: 'en-US', FriendlyName: 'Microsoft AndrewNeural (Male) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, AriaNeural)', ShortName: 'en-US-AriaNeural', Gender: 'Female', Locale: 'en-US', FriendlyName: 'Microsoft AriaNeural (Female) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, ChristopherNeural)', ShortName: 'en-US-ChristopherNeural', Gender: 'Male', Locale: 'en-US', FriendlyName: 'Microsoft ChristopherNeural (Male) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, DavisNeural)', ShortName: 'en-US-DavisNeural', Gender: 'Male', Locale: 'en-US', FriendlyName: 'Microsoft DavisNeural (Male) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, EmmaNeural)', ShortName: 'en-US-EmmaNeural', Gender: 'Female', Locale: 'en-US', FriendlyName: 'Microsoft EmmaNeural (Female) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, EricNeural)', ShortName: 'en-US-EricNeural', Gender: 'Male', Locale: 'en-US', FriendlyName: 'Microsoft EricNeural (Male) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, GuyNeural)', ShortName: 'en-US-GuyNeural', Gender: 'Male', Locale: 'en-US', FriendlyName: 'Microsoft GuyNeural (Male) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, JennyNeural)', ShortName: 'en-US-JennyNeural', Gender: 'Female', Locale: 'en-US', FriendlyName: 'Microsoft JennyNeural (Female) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, MichelleNeural)', ShortName: 'en-US-MichelleNeural', Gender: 'Female', Locale: 'en-US', FriendlyName: 'Microsoft MichelleNeural (Female) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, RogerNeural)', ShortName: 'en-US-RogerNeural', Gender: 'Male', Locale: 'en-US', FriendlyName: 'Microsoft RogerNeural (Male) en-US' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-US, StephenNeural)', ShortName: 'en-US-StephenNeural', Gender: 'Male', Locale: 'en-US', FriendlyName: 'Microsoft StephenNeural (Male) en-US' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (en-GB, AlfieNeural)', ShortName: 'en-GB-AlfieNeural', Gender: 'Male', Locale: 'en-GB', FriendlyName: 'Microsoft AlfieNeural (Male) en-GB' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-GB, EthanNeural)', ShortName: 'en-GB-EthanNeural', Gender: 'Male', Locale: 'en-GB', FriendlyName: 'Microsoft EthanNeural (Male) en-GB' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-GB, HollieNeural)', ShortName: 'en-GB-HollieNeural', Gender: 'Female', Locale: 'en-GB', FriendlyName: 'Microsoft HollieNeural (Female) en-GB' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-GB, LibbyNeural)', ShortName: 'en-GB-LibbyNeural', Gender: 'Female', Locale: 'en-GB', FriendlyName: 'Microsoft LibbyNeural (Female) en-GB' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-GB, MaisieNeural)', ShortName: 'en-GB-MaisieNeural', Gender: 'Female', Locale: 'en-GB', FriendlyName: 'Microsoft MaisieNeural (Female) en-GB' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-GB, NoahNeural)', ShortName: 'en-GB-NoahNeural', Gender: 'Male', Locale: 'en-GB', FriendlyName: 'Microsoft NoahNeural (Male) en-GB' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-GB, OliverNeural)', ShortName: 'en-GB-OliverNeural', Gender: 'Male', Locale: 'en-GB', FriendlyName: 'Microsoft OliverNeural (Male) en-GB' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-GB, OliviaNeural)', ShortName: 'en-GB-OliviaNeural', Gender: 'Female', Locale: 'en-GB', FriendlyName: 'Microsoft OliviaNeural (Female) en-GB' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (en-AU, AnnetteNeural)', ShortName: 'en-AU-AnnetteNeural', Gender: 'Female', Locale: 'en-AU', FriendlyName: 'Microsoft AnnetteNeural (Female) en-AU' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-AU, CarlyNeural)', ShortName: 'en-AU-CarlyNeural', Gender: 'Female', Locale: 'en-AU', FriendlyName: 'Microsoft CarlyNeural (Female) en-AU' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-AU, DarrenNeural)', ShortName: 'en-AU-DarrenNeural', Gender: 'Male', Locale: 'en-AU', FriendlyName: 'Microsoft DarrenNeural (Male) en-AU' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-AU, DuncanNeural)', ShortName: 'en-AU-DuncanNeural', Gender: 'Male', Locale: 'en-AU', FriendlyName: 'Microsoft DuncanNeural (Male) en-AU' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-AU, ElsieNeural)', ShortName: 'en-AU-ElsieNeural', Gender: 'Female', Locale: 'en-AU', FriendlyName: 'Microsoft ElsieNeural (Female) en-AU' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-AU, GraceNeural)', ShortName: 'en-AU-GraceNeural', Gender: 'Female', Locale: 'en-AU', FriendlyName: 'Microsoft GraceNeural (Female) en-AU' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-AU, JackNeural)', ShortName: 'en-AU-JackNeural', Gender: 'Male', Locale: 'en-AU', FriendlyName: 'Microsoft JackNeural (Male) en-AU' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-AU, NatashaNeural)', ShortName: 'en-AU-NatashaNeural', Gender: 'Female', Locale: 'en-AU', FriendlyName: 'Microsoft NatashaNeural (Female) en-AU' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (en-CA, ClaraNeural)', ShortName: 'en-CA-ClaraNeural', Gender: 'Female', Locale: 'en-CA', FriendlyName: 'Microsoft ClaraNeural (Female) en-CA' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (en-CA, LiamNeural)', ShortName: 'en-CA-LiamNeural', Gender: 'Male', Locale: 'en-CA', FriendlyName: 'Microsoft LiamNeural (Male) en-CA' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, AmalaNeural)', ShortName: 'de-DE-AmalaNeural', Gender: 'Female', Locale: 'de-DE', FriendlyName: 'Microsoft AmalaNeural (Female) de-DE' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, ChristophNeural)', ShortName: 'de-DE-ChristophNeural', Gender: 'Male', Locale: 'de-DE', FriendlyName: 'Microsoft ChristophNeural (Male) de-DE' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, ElkeNeural)', ShortName: 'de-DE-ElkeNeural', Gender: 'Female', Locale: 'de-DE', FriendlyName: 'Microsoft ElkeNeural (Female) de-DE' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, FlorianNeural)', ShortName: 'de-DE-FlorianNeural', Gender: 'Male', Locale: 'de-DE', FriendlyName: 'Microsoft FlorianNeural (Male) de-DE' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, GiselaNeural)', ShortName: 'de-DE-GiselaNeural', Gender: 'Female', Locale: 'de-DE', FriendlyName: 'Microsoft GiselaNeural (Female) de-DE' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, KasperNeural)', ShortName: 'de-DE-KasperNeural', Gender: 'Male', Locale: 'de-DE', FriendlyName: 'Microsoft KasperNeural (Male) de-DE' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, KatjaNeural)', ShortName: 'de-DE-KatjaNeural', Gender: 'Female', Locale: 'de-DE', FriendlyName: 'Microsoft KatjaNeural (Female) de-DE' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, KonradNeural)', ShortName: 'de-DE-KonradNeural', Gender: 'Male', Locale: 'de-DE', FriendlyName: 'Microsoft KonradNeural (Male) de-DE' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (de-DE, KyanNeural)', ShortName: 'de-DE-KyanNeural', Gender: 'Male', Locale: 'de-DE', FriendlyName: 'Microsoft KyanNeural (Male) de-DE' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, AlodieNeural)', ShortName: 'fr-FR-AlodieNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft AlodieNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, AntoineNeural)', ShortName: 'fr-FR-AntoineNeural', Gender: 'Male', Locale: 'fr-FR', FriendlyName: 'Microsoft AntoineNeural (Male) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, BernardNeural)', ShortName: 'fr-FR-BernardNeural', Gender: 'Male', Locale: 'fr-FR', FriendlyName: 'Microsoft BernardNeural (Male) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, BrigitteNeural)', ShortName: 'fr-FR-BrigitteNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft BrigitteNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, CelesteNeural)', ShortName: 'fr-FR-CelesteNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft CelesteNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, ClaudeNeural)', ShortName: 'fr-FR-ClaudeNeural', Gender: 'Male', Locale: 'fr-FR', FriendlyName: 'Microsoft ClaudeNeural (Male) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, ClementineNeural)', ShortName: 'fr-FR-ClementineNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft ClementineNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, DeniseNeural)', ShortName: 'fr-FR-DeniseNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft DeniseNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, EloiseNeural)', ShortName: 'fr-FR-EloiseNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft EloiseNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, HenriNeural)', ShortName: 'fr-FR-HenriNeural', Gender: 'Male', Locale: 'fr-FR', FriendlyName: 'Microsoft HenriNeural (Male) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, JacquelineNeural)', ShortName: 'fr-FR-JacquelineNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft JacquelineNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, JeromeNeural)', ShortName: 'fr-FR-JeromeNeural', Gender: 'Male', Locale: 'fr-FR', FriendlyName: 'Microsoft JeromeNeural (Male) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, JosephineNeural)', ShortName: 'fr-FR-JosephineNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft JosephineNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, MauricetteNeural)', ShortName: 'fr-FR-MauricetteNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft MauricetteNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, PaulNeural)', ShortName: 'fr-FR-PaulNeural', Gender: 'Male', Locale: 'fr-FR', FriendlyName: 'Microsoft PaulNeural (Male) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, RemyNeural)', ShortName: 'fr-FR-RemyNeural', Gender: 'Male', Locale: 'fr-FR', FriendlyName: 'Microsoft RemyNeural (Male) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, SabineNeural)', ShortName: 'fr-FR-SabineNeural', Gender: 'Female', Locale: 'fr-FR', FriendlyName: 'Microsoft SabineNeural (Female) fr-FR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (fr-FR, YvesNeural)', ShortName: 'fr-FR-YvesNeural', Gender: 'Male', Locale: 'fr-FR', FriendlyName: 'Microsoft YvesNeural (Male) fr-FR' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, AbrilNeural)', ShortName: 'es-ES-AbrilNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft AbrilNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, AlvaroNeural)', ShortName: 'es-ES-AlvaroNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft AlvaroNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, AntonioNeural)', ShortName: 'es-ES-AntonioNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft AntonioNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, AraceliNeural)', ShortName: 'es-ES-AraceliNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft AraceliNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, CamilaNeural)', ShortName: 'es-ES-CamilaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft CamilaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, CarlosNeural)', ShortName: 'es-ES-CarlosNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft CarlosNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, CarmenNeural)', ShortName: 'es-ES-CarmenNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft CarmenNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, CesarNeural)', ShortName: 'es-ES-CesarNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft CesarNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, ConchitaNeural)', ShortName: 'es-ES-ConchitaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft ConchitaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, DavidNeural)', ShortName: 'es-ES-DavidNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft DavidNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, DonatoNeural)', ShortName: 'es-ES-DonatoNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft DonatoNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, ElviraNeural)', ShortName: 'es-ES-ElviraNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft ElviraNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, EmiliaNeural)', ShortName: 'es-ES-EmiliaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft EmiliaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, FedericoNeural)', ShortName: 'es-ES-FedericoNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft FedericoNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, InesNeural)', ShortName: 'es-ES-InesNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft InesNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, JavierNeural)', ShortName: 'es-ES-JavierNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft JavierNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, LaiaNeural)', ShortName: 'es-ES-LaiaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft LaiaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, LeonardoNeural)', ShortName: 'es-ES-LeonardoNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft LeonardoNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, LiaNeural)', ShortName: 'es-ES-LiaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft LiaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, LuzNeural)', ShortName: 'es-ES-LuzNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft LuzNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, MartinNeural)', ShortName: 'es-ES-MartinNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft MartinNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, MónicaNeural)', ShortName: 'es-ES-MónicaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft MónicaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, NicolásNeural)', ShortName: 'es-ES-NicolásNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft NicolásNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, NoeliaNeural)', ShortName: 'es-ES-NoeliaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft NoeliaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, PilarNeural)', ShortName: 'es-ES-PilarNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft PilarNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, RafaelNeural)', ShortName: 'es-ES-RafaelNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft RafaelNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, RebecaNeural)', ShortName: 'es-ES-RebecaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft RebecaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, SaraNeural)', ShortName: 'es-ES-SaraNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft SaraNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, SergioNeural)', ShortName: 'es-ES-SergioNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft SergioNeural (Male) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, TrianaNeural)', ShortName: 'es-ES-TrianaNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft TrianaNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, VeraNeural)', ShortName: 'es-ES-VeraNeural', Gender: 'Female', Locale: 'es-ES', FriendlyName: 'Microsoft VeraNeural (Female) es-ES' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (es-ES, Yon GonzálezNeural)', ShortName: 'es-ES-YonGonzálezNeural', Gender: 'Male', Locale: 'es-ES', FriendlyName: 'Microsoft Yon GonzálezNeural (Male) es-ES' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, AnnaNeural)', ShortName: 'it-IT-AnnaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft AnnaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, AntonioNeural)', ShortName: 'it-IT-AntonioNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft AntonioNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, BenignoNeural)', ShortName: 'it-IT-BenignoNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft BenignoNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, BrunelloNeural)', ShortName: 'it-IT-BrunelloNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft BrunelloNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, CarlaNeural)', ShortName: 'it-IT-CarlaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft CarlaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, CatelloNeural)', ShortName: 'it-IT-CatelloNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft CatelloNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, DiegoNeural)', ShortName: 'it-IT-DiegoNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft DiegoNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, ElsaNeural)', ShortName: 'it-IT-ElsaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft ElsaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, FabioNeural)', ShortName: 'it-IT-FabioNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft FabioNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, FilippoNeural)', ShortName: 'it-IT-FilippoNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft FilippoNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, FrancescaNeural)', ShortName: 'it-IT-FrancescaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft FrancescaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, GiannaNeural)', ShortName: 'it-IT-GiannaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft GiannaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, GioacchinoNeural)', ShortName: 'it-IT-GioacchinoNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft GioacchinoNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, IsabellaNeural)', ShortName: 'it-IT-IsabellaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft IsabellaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, LalataNeural)', ShortName: 'it-IT-LalataNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft LalataNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, LeilaNeural)', ShortName: 'it-IT-LeilaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft LeilaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, LivioNeural)', ShortName: 'it-IT-LivioNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft LivioNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, LuciaNeural)', ShortName: 'it-IT-LuciaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft LuciaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, MattiaNeural)', ShortName: 'it-IT-MattiaNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft MattiaNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, MimmoNeural)', ShortName: 'it-IT-MimmoNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft MimmoNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, NicolettaNeural)', ShortName: 'it-IT-NicolettaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft NicolettaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, PaoloNeural)', ShortName: 'it-IT-PaoloNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft PaoloNeural (Male) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, PierinaNeural)', ShortName: 'it-IT-PierinaNeural', Gender: 'Female', Locale: 'it-IT', FriendlyName: 'Microsoft PierinaNeural (Female) it-IT' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (it-IT, RoccoNeural)', ShortName: 'it-IT-RoccoNeural', Gender: 'Male', Locale: 'it-IT', FriendlyName: 'Microsoft RoccoNeural (Male) it-IT' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, AoiNeural)', ShortName: 'ja-JP-AoiNeural', Gender: 'Female', Locale: 'ja-JP', FriendlyName: 'Microsoft AoiNeural (Female) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, DaikiNeural)', ShortName: 'ja-JP-DaikiNeural', Gender: 'Male', Locale: 'ja-JP', FriendlyName: 'Microsoft DaikiNeural (Male) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, HarukaNeural)', ShortName: 'ja-JP-HarukaNeural', Gender: 'Female', Locale: 'ja-JP', FriendlyName: 'Microsoft HarukaNeural (Female) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, HimariNeural)', ShortName: 'ja-JP-HimariNeural', Gender: 'Female', Locale: 'ja-JP', FriendlyName: 'Microsoft HimariNeural (Female) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, IchiroNeural)', ShortName: 'ja-JP-IchiroNeural', Gender: 'Male', Locale: 'ja-JP', FriendlyName: 'Microsoft IchiroNeural (Male) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, KeitaNeural)', ShortName: 'ja-JP-KeitaNeural', Gender: 'Male', Locale: 'ja-JP', FriendlyName: 'Microsoft KeitaNeural (Male) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, MaiNeural)', ShortName: 'ja-JP-MaiNeural', Gender: 'Female', Locale: 'ja-JP', FriendlyName: 'Microsoft MaiNeural (Female) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, NanamiNeural)', ShortName: 'ja-JP-NanamiNeural', Gender: 'Female', Locale: 'ja-JP', FriendlyName: 'Microsoft NanamiNeural (Female) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, NaokiNeural)', ShortName: 'ja-JP-NaokiNeural', Gender: 'Male', Locale: 'ja-JP', FriendlyName: 'Microsoft NaokiNeural (Male) ja-JP' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ja-JP, ShioriNeural)', ShortName: 'ja-JP-ShioriNeural', Gender: 'Female', Locale: 'ja-JP', FriendlyName: 'Microsoft ShioriNeural (Female) ja-JP' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, BongJinNeural)', ShortName: 'ko-KR-BongJinNeural', Gender: 'Male', Locale: 'ko-KR', FriendlyName: 'Microsoft BongJinNeural (Male) ko-KR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, GookMinNeural)', ShortName: 'ko-KR-GookMinNeural', Gender: 'Male', Locale: 'ko-KR', FriendlyName: 'Microsoft GookMinNeural (Male) ko-KR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, InJoonNeural)', ShortName: 'ko-KR-InJoonNeural', Gender: 'Male', Locale: 'ko-KR', FriendlyName: 'Microsoft InJoonNeural (Male) ko-KR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, JiMinNeural)', ShortName: 'ko-KR-JiMinNeural', Gender: 'Female', Locale: 'ko-KR', FriendlyName: 'Microsoft JiMinNeural (Female) ko-KR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, SeoHyeonNeural)', ShortName: 'ko-KR-SeoHyeonNeural', Gender: 'Female', Locale: 'ko-KR', FriendlyName: 'Microsoft SeoHyeonNeural (Female) ko-KR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, SeoYunNeural)', ShortName: 'ko-KR-SeoYunNeural', Gender: 'Female', Locale: 'ko-KR', FriendlyName: 'Microsoft SeoYunNeural (Female) ko-KR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, ShinBiNeural)', ShortName: 'ko-KR-ShinBiNeural', Gender: 'Female', Locale: 'ko-KR', FriendlyName: 'Microsoft ShinBiNeural (Female) ko-KR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, SoonBokNeural)', ShortName: 'ko-KR-SoonBokNeural', Gender: 'Female', Locale: 'ko-KR', FriendlyName: 'Microsoft SoonBokNeural (Female) ko-KR' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (ko-KR, SunHiNeural)', ShortName: 'ko-KR-SunHiNeural', Gender: 'Female', Locale: 'ko-KR', FriendlyName: 'Microsoft SunHiNeural (Female) ko-KR' },

  { Name: 'Microsoft Server Speech Text to Speech Voice (vi-VN, HoaiMyNeural)', ShortName: 'vi-VN-HoaiMyNeural', Gender: 'Female', Locale: 'vi-VN', FriendlyName: 'Microsoft HoaiMyNeural (Female) vi-VN' },
  { Name: 'Microsoft Server Speech Text to Speech Voice (vi-VN, NamMinhNeural)', ShortName: 'vi-VN-NamMinhNeural', Gender: 'Male', Locale: 'vi-VN', FriendlyName: 'Microsoft NamMinhNeural (Male) vi-VN' },
];

export default async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  res.status(200).json(VOICES);
}
